name: Godlike
main: me.marcoboekholt.mabonew.main
version: 1.0
description: >
             my first plugin

commands:
  Sword:
    description: Get sword with all enchantments
  Armour:
    description: Get armour with all enchantments
  Bow:
    description: Get bow with all enchantments
  Tools:
    description: Get tools with all enchantments
  God:
    description: Get Golden apple effect