name: Godlike
main: me.marcoboekholt.mabonew.main
version: 1.0
author: Marco Boekholt
description: >
             my first plugin

commands:
  Sword:
    description: Get sword with all enchantments
    permissions: Godlike.sword
  Armour:
    description: Get armour with all enchantments
    permissions: Godlike.armour
  Bow:
    description: Get bow with all enchantments
    permissions: Godlike.bow
  Tools:
    description: Get tools with all enchantments
    permissions: Godlike.tools
  God:
    description: Get Golden apple effect
    permissions: Godlike.god
  power:
    description: Get defence and strenght power
    permissions: Godlike.power
  fly:
    description: Get fly powers!
    permissions: Godlike.fly
  speed:
    description: Walk faster then normal
    permissions: Godlike.speed
    
permissions:
   Godlike.*:
     description: Gives access to all Godlike commands
     children:
       Godlike.sword: true
       Godlike.armour: true
       Godlike.bow: true
       Godlike.tools: true
       Godlike.god: true
       Godlike.power: true
       Godlike.fly: true
       Godlike.speed: true
   Godlike.sword:
     description: Allows you to get a Diamond sword!
     default: op
   Godlike.armour:
     description: Allows you to get Diamond armour!
     default: op
   Godlike.bow:
     description: AAllows you to get a Bow with Arrows!
     default: op
   Godlike.tools:
     description: Allows you to get a Diamond tools!
     default: op
   Godlike.god:
     description: Allows you to get Golden Apple effect!
     default: op
   Godlike.power:
     description: Allows you to get Defence and Strenght power!
     default: op
   Godlike.fly:
     description: Allows you to go fly!
     default: op
   Godlike.speed:
     description: Allows you to run faster!
     default: op