name: Godlike
main: me.marcoboekholt.godlike.main
version: 3.0
author: Marco Boekholt
description: This plugin will give you the highest possible enchantment on armour and weapons.

commands:
  God:
    permissions: Godlike.*
    
permissions:
   Godlike.*:
     description: Gives you access to all Godlike commands
     default: op
     children:
       Godlike.sword: true
       Godlike.armour: true
       Godlike.bow: true
       Godlike.tools: true
       Godlike.horse: true
       Godlike.apple: true
       Godlike.power: true
       Godlike.speed: true
   Godlike.sword:
     description: Allows you to use the sword command
     default: op
   Godlike.armour:
     description: Allows you to use the armour command
     default: op
   Godlike.bow:
     description: Allows you to use the bow command
     default: op
   Godlike.tools:
     description: Allows you to use the tools command
     default: op
   Godlike.horse:
     description: Allows you to use the horse command to get horse armour and saddle
     default: op
   Godlike.apple:
     description: Allows you to get the golden apple effects
     default: op
   Godlike.power:
     description: Allows you to get Defence and Strength powers
     default: op
   Godlike.speed:
     description: Allows you to walk faster than normal
     default: op
   Cooldown.bypass:
     description: Allows you to bypass the cooldown
     default: op